branches:
  except:
    - /dev.*/  # do not build dev branch

image:
  - Visual Studio 2017

platform:
  - x86

configuration:
  - Debug
  - Release

cache: c:\tools\vcpkg\installed\ -> .appveyor.yml  # cache the installed vcpkg packages

install:
  - powershell .\scripts\prepare.ps1 C:\tools\vcpkg

build_script:
  - powershell .\scripts\generate.ps1 %CONFIGURATION%
  - powershell .\scripts\build.ps1 %CONFIGURATION%
