branches:
  except:
    - /dev.*/  # do not build dev branch

image:
  - Visual Studio 2017

platform:
  - x86

configuration:
  - Debug
  - Release

environment:
  VCPKG_ROOT: C:\tools\vcpkg

cache: c:\tools\vcpkg\installed\ -> .appveyor.yml  # cache the installed vcpkg packages

install:
  - git submodule init
  - git submodule update
  - powershell .\scripts\prepare.ps1 %VCPKG_ROOT%

build_script:
  - powershell .\scripts\generate.ps1 %CONFIGURATION%
  - powershell .\scripts\build.ps1 %CONFIGURATION%
